"""update

Revision ID: db3d1083d014
Revises: 3dd3974e6f10
Create Date: 2023-05-06 12:35:23.839767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3d1083d014'
down_revision = '3dd3974e6f10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country', table_name='performance')
    op.drop_index('iso', table_name='performance')
    op.drop_index('name', table_name='performance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'performance', ['name'], unique=False)
    op.create_index('iso', 'performance', ['iso'], unique=False)
    op.create_index('country', 'performance', ['country'], unique=False)
    # ### end Alembic commands ###
